"""Injects model results and evidence tables into the dashboard template -> dashboard/index.html"""
import json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
res = json.load(open(os.path.join(HERE, "..", "model", "results.json")))
params = json.load(open(os.path.join(HERE, "..", "model", "params.json")))
V = lambda node: node["value"] if isinstance(node, dict) and "value" in node else node
hp = params["routes"]["hybrid_2blocks_2y"]; g = params["general"]
P = {k: V(hp[k]) for k in ("multiple_median","seller_finance_share","vendor_loan_term_years","vendor_loan_rate","manager_cost")}
P.update({k: V(g[k]) for k in ("pg_share_of_facility","senior_debt_max_ebitda_multiple","dscr_min")})

def slim(r):
    keep = ("route","kind","p_target_by_2034","p_500k_by_2034","p_floor_breached","p_business_acquired","p_business_failed","p_sold","mean_employed_days_total","nw_percentiles_2034","median_owner_draw_when_operating","mean_hours_by_year","fan","years","conditional")
    return {k: r[k] for k in keep}
data = {
 "routes_fit": {k: slim(v) for k, v in res["routes_fit"].items()},
 "routes_raw": {k: {"p_target_by_2034": v["p_target_by_2034"], "p_500k_by_2034": v["p_500k_by_2034"]} for k, v in res["routes_raw"].items()},
 "sweep_labour": res["sweep_labour"], "tornado": res["tornado"], "scenarios": res["scenarios"], "horizon": res["horizon"], "params": P,
}
fitrows = [
 ("hybrid_2blocks_2y","selling","low","yes","15 → 20","manager leaves (35%); seller-dependency; one supplier line", "Selling and sourcing seat is the proven mode (age-22 business, Etsy); takeovers survive better than start-ups in years 1–2 (French cohort OR 0.46); detail-orientation 15% raises DD risk."),
 ("buy_distributor","selling","low","yes","35 → 20","exclusive agreement termination (2–3 yr terms, 3–12 months' notice)", "Wholesale payroll only 16% of revenue so a salaried manager is affordable; 0 of 31 listings offer vendor finance; only 2 of 31 say management can absorb the owner's role."),
 ("buy_services","selling","medium","yes","35 → 22","wage floor (NLW +4.1%, employer NIC 15%) on ~50% payroll", "Owner-led cleaning firms earn 21% net but 8.5% once the owner stops doing the work (Plimsoll 2026): the margin is the owner's labour."),
 ("buy_hire","mixed","medium","yes","35 → 22","fleet capex; construction output −2.5–3.3% in 2026", "Asset-backed and bankable; but hire owners in the listings operate the kit and depots are provincial; asks anchor on fleet value (3.4×)."),
 ("buy_logistics","mixed","medium","yes","38 → 25","driver dependence; ~2% haulage margin; lowest 5-yr survival sector", "Retiring owners are commonest here (42%) and manager-in-place is stated most (25%), but margins leave no slack for a non-operator."),
 ("buy_ecommerce","mixed","medium","partly","30 → 20","Amazon-only (5 of 13 EF listings); Etsy take rate 24.2%", "The Etsy playbook fits; 'cannot create demand from nothing' does not. Sold multiples 1.4–2.0× vs asks 2.2–3.6×."),
 ("buy_saas","technical","high","yes","35 → 30","founder-dependent code; churn", "'The buyer is largely purchasing a job' (FE International). Implementer is the lowest archetype; 0/6 solo builds."),
 ("buy_agency","technical","high","yes","40 → 30","key person; unpriced labour (the Rock lesson)", "Most sub-£300k agencies are owner-delivered; only 5 of 17 clearly have teams."),
 ("build_services","mixed","high","partly","45 → 30","owner is the workforce in year 1", "Year one is five-day operator work with no manager: the shape the SOT says health cannot sustain (IBD work impairment 39%, fatigue OR 4.3)."),
 ("build_ecommerce","technical","high","no","40 → 25","platform; 3-yr survival 35.8% (SIC 479)", "Three demand-creation attempts failed; online retail has the second-worst 3-year survival of any 3-digit sector."),
 ("build_aws_partner","selling","high","partly","40 → 35","founder is the delivery capacity", "Contracting under a brand until a team exists; only 3% of UK computer consultancies exceed £1m turnover; Capita ended after five weeks of sustained delivery."),
 ("build_ai_app","technical","high","no","35 → 30","product-market fit (43% of post-mortems)", "0/6 solo builds; SOT's own 20–30% odds; a second person and warm customers help (Howell & Hall 2026) but do not change the base rate."),
 ("hybrid_plan_app","selling","medium","yes","15 → 28","the app is optional and killable", "The version of the app bet the evidence favours: customers already owned, second person implements, capital from the risk pot two years after completion."),
]
data["fit"] = [{"route":r,"seat":s,"impl":i,"demand":d,"hours":h,"risk":k,"fit":V(params["routes"][r]["fit_multiplier"]),"why":w} for r,s,i,d,h,k,w in fitrows]
data["market"] = [
 {"cat":"Importer / distributor / wholesaler","n":"14 priced (31 core)","ask":"£295,000","profit":"£211,500 (n=10, incl. offers-invited)","mult":"1.4× and 4.0× (only 2 publish both)","ret":"39%","vf":"0%","se":"23%","mgr":"6%","note":"BFS/Daltons/BSR headline counts (1,475/178/138) overstate the pool ~100-fold; exclusive agreements stated on 26%. ONS wholesale 5-yr survival 41.7%."},
 {"cat":"Contracted B2B services","n":"23 (12 in £200–450k)","ask":"£285,000","profit":"£99,000 (n=12)","mult":"2.50× (2.27× excl. outliers)","ret":"9%","vf":"0%","se":"30%","mgr":"4%","note":"SE supply is here (grounds portfolios, security, window cleaning). Cleaning 5-yr survival 47.5%; 164 cleaning insolvencies in 12 months (flat)."},
 {"cat":"Hire (plant, tool, container, event)","n":"15 (10 in band)","ask":"£399,950","profit":"£107,000 (n=5)","mult":"3.36×","ret":"13%","vf":"0%","se":"7%","mgr":"13%","note":"Priced on kit (£150–300k asset values); machinery-hire insolvencies +20% y/y off a small base."},
 {"cat":"Small logistics (courier, haulage, 3PL)","n":"12 (6 in band)","ask":"£324,950","profit":"£125,000 (n=7)","mult":"2.61×","ret":"42%","vf":"0%","se":"17%","mgr":"25%","note":"Some asks at 0.16–0.3× turnover; 49% of haulage firms started since 2019 have closed (RHA); road freight insolvencies 372/yr."},
 {"cat":"Existing multi-channel ecommerce","n":"~4–9 genuine UK in band","ask":"varies","profit":"—","mult":"asks 2.2–3.6×; sold 1.4–2.0×","ret":"—","vf":"earn-outs on 30–34% (EF)","se":"—","mgr":"rare","note":"Empire Flippers 2025: 161 sold of 8,540 submissions (1.9%); avg sold business 5.7 years old; 71% of ecommerce deals are Amazon FBA."},
 {"cat":"Small SaaS with paying customers","n":"17 (thin in £50–300k ARR)","ask":"—","profit":"—","mult":"3.9× profit (Acquire.com 2024–25)","ret":"—","vf":"—","se":"—","mgr":"solo/duo founders","note":"81 days on market; sell-through unpublished; 'buyer is purchasing a job' under $1m ARR."},
 {"cat":"Agency / MSP (control)","n":"17","ask":"£200k on £43k EBITDA (one disclosed)","profit":"—","mult":"4.65× (asks 0.8–2× turnover)","ret":"—","vf":"—","se":"—","mgr":"5 of 17 have teams","note":"Consult EFC: 1.5–3× for under-£300k EBITDA SMEs with an owner-dependency discount."},
 {"cat":"BUILD: multi-channel ecommerce","n":"n/a","ask":"capital £30–60k","profit":"HMRC: 3.8% of wholesale/retail self-employed earn ≥£50k","mult":"resale 1.4–1.55× (Flippa 2025–26)","ret":"—","vf":"—","se":"—","mgr":"—","note":"ONS SIC 479: 3-yr survival 35.8%, 5-yr 17.7%; Jungle Scout: 47% under $25k lifetime profit, 30% ever above $50k."},
 {"cat":"BUILD: B2B services","n":"n/a","ask":"capital £10–60k","profit":"5.2% of all self-employed ≥£50k","mult":"resale ~1.2–1.5×","ret":"—","vf":"—","se":"—","mgr":"—","note":"ONS SIC 812: 3-yr survival 58–68%, 5-yr 47.5%; owner hours ~39–51/wk (Tide 2026, Enterprise Nation)."},
 {"cat":"BUILD: AWS / AI consultancy","n":"n/a","ask":"capital £5–25k","profit":"£70k ≈ 140 billed days","mult":"1.5–3× SDE with owner-dependency discount","ret":"—","vf":"—","se":"—","mgr":"—","note":"ONS info & comms 3-yr survival 56%, 5-yr 37%; 3% of computer consultancies exceed £1m turnover; 96 AWS-partner deals globally 2015–25, 14 UK."},
 {"cat":"BUILD: AI app / vertical SaaS","n":"n/a","ask":"£33–58k dev + infra","profit":"70% of indie products <$1k MRR","mult":"3.9× profit; Govtech→Netcall 3.7× revenue","ret":"—","vf":"—","se":"—","mgr":"—","note":"ChartMogul: 13.4% reach $1m ARR within 3 years; G-Cloud 13: 23% of suppliers won any call-off; 22-month public-sector buying cycle."},
]
data["decisions"] = [
 {"t":"The plan's arithmetic does not reconcile; fix the inputs before the November sizing session.","b":"The SOT counts a £120k floor plus a £50–70k risk pot, but ~£120k now plus £50k incoming is £150–170k, which leaves £30–50k above the floor. A £300k deal needs £110–130k above the floor (deposit, costs, working-capital reserve). Either the risk pot is real and the floor is smaller, or the deal is smaller. Start cash is the single biggest lever in the tornado."},
 {"t":"One block a year is the coast, not the deposit.","b":"One 13-week block nets about £23k as sole income against a £20k burn. On the one-block rule cash never accumulates and the deal closes about 19% of the time. Two blocks a year for two years (roughly 180 billed days total) doubles the close rate; three blocks a year is where the SOT says health breaks. This is a labour-versus-time trade the model can show but cannot decide."},
 {"t":"Buy on services or logistics pricing, not on distributor pricing.","b":"Entry multiple is the second-biggest lever: 2.0× against 3.6× moves P(£750k) from 10% to 1%. The listing scan shows contracted services at 2.5× and logistics at 2.6× with the South East supply concentrated in services; distributors in the envelope are few (14 priced) and priced on turnover. The lead-candidate category is the thinnest market, not the cheapest."},
 {"t":"Expect a near-zero draw for three to four years, and write it into the kill criteria.","b":"At 2.8× with three-quarters debt, the owner draw after manager cover and debt service is close to zero until the vendor note clears (median by year held in section 3). The £70–80k draw in the SOT needs a £450k+ business or half the leverage. The odd contract after 100 days is not a top-up in this plan; it is the plan's cash flow."},
 {"t":"Negotiate the note, not the price.","b":"A 50% vendor note over four years and a 10-year GGS term change the draw more than a 10% price cut does; the finance notes show 10-year GGS terms were announced in July 2026 but lenders still show 6 years, and 0 of 81 scanned listings advertise vendor finance, so this will be won in the room, which is the seat Dale is good at."},
 {"t":"Re-frame the number: £500k by 40, £750k by 42–44.","b":"Every route clears £500k by 2034 far more often than £750k, and the horizon chart shows the plan's odds of £750k roughly doubling by 2036. The passive-income test (£30k a year) is met at £750k; £500k funds the burn. Holding the 2034 date and the £750k number together forces either more labour or more leverage than the SOT allows."},
 {"t":"The AI app stays an option, in the form the evidence supports.","b":"Built cold with a second person it sits at 2–9% with a 60% floor-breach rate; built two years after completion for customers Dale already owns, from the risk pot, it adds about one point to the plan's odds and lifts the exit value if it works. That is the SOT's own '10% argument' and the data agrees with it. The AWS consultancy scores higher on money but is contracting under a brand: 40 hours a week of selling and delivering."},
 {"t":"Keep the five real sets of accounts as the decision, not this model.","b":"The model's least certain inputs are the deal-close rate for a part-time UK buyer (no UK cohort exists), the incremental manager cost, and vendor-finance share. Five sets of accounts with stated owner roles and a lender conversation resolve all three; nothing on this page should reopen buy-versus-build, which the data supports as settled."},
]
data["method"] = """<p><b>Model.</b> <code>model/mc_model.py</code> simulates 20,000 paths per route from end-2026 to end-2034. Each year: index return on liquid cash (5.5% nominal, sd 15%), £20k burn, planned contracting blocks, search and completion (deal sized to the cash above the £120k floor, bank debt capped by personal-guarantee share, 2× EBITDA and a 1.3 DSCR), a year-one shock (manager leaves 35%, severe decline 12%), growth, failure hazard, owner draw after manager cover and debt service, optional sale at the entry multiple from year 3, and the SC-contracting backstop whenever cash threatens the floor. Net worth counts business equity at entry multiple less debt.</p>
<p><b>Parameters.</b> 380 leaves in <code>model/params.json</code>, each with value, range, source and a confidence tag (measured / derived / inferred); <code>model/params_evidence.md</code> is the audit trail. Fit multipliers (section 8) are the only judgement inputs and are shown alongside raw results.</p>
<p><b>Evidence.</b> 13 research notes in <code>research_notes/Path to 750k by 40/</code>: live listings (3 scans, 81 priced UK listings plus 61 digital comps), UK deal multiples (Dealsuite H1 2026, MarktoMarket, UK200), acquisition finance (GGS, Funding Circle, Allica, Bank Rate 3.75%), post-acquisition base rates (Stanford/IESE/Yale search-fund studies, SIG self-funded study, French INSEE takeover cohort, SBA charge-offs), build-from-zero base rates (ONS Business Demography 2024, HMRC SPI 2023-24, Jungle Scout, Flippa, Empire Flippers), sector economics (Insolvency Service Aug 2026, Plimsoll, ONS ASHE, Indeed), contracting rates (ITJobsWatch to 28 Sep 2026, IPSE, Qdos), returns and tax (Vanguard, JPM, AQR, UBS yearbook, gov.uk 2026/27 rates, BADR 18%), health and personality (JCC 2024 IBD meta-analysis, Rauch & Frese 2007, Zhao & Seibert 2006/2010, Gollwitzer & Sheeran 2006), UK buyer cases (Acquiring Minds, Business Sale Report, UK Business Forums) and the AWS-partner / AI-app note (APN tiers, ChartMogul, MicroConf, Acquire.com, Tussell, G-Cloud).</p>
<p><b>Limits.</b> BusinessesForSale and Rightbiz listing pages, BDO PCPI and British Business Bank pages were bot-blocked; every researcher exhausted its web-search budget, so some figures come from search excerpts corroborated by secondary sources. No UK data exists for acquired-versus-founded survival, post-acquisition owner hours, sell-through rates or vendor-finance prevalence; those are inferred and flagged. The full report is <code>reports/Path to 750k by 40.md</code>.</p>"""
tpl = open(os.path.join(HERE, "template.html")).read()
html = tpl.replace("/*DATA*/{}/*END*/", json.dumps(data, separators=(",", ":")))
open(os.path.join(HERE, "index.html"), "w").write(html)
print("built", len(html))
